
api:
  origin: http://localhost:3000
  port: 43210

hostLink:
  hostAuthKey: SuperSecretKey
  port: 43211

tls:
  use: false
  cert:
    key: /etc/letsencrypt/live/privkey.pem
    cert: /etc/letsencrypt/live/fullchain.pem
    ca: /etc/letsencrypt/live/chain.pem

auth:
  salt: secret
  verifyLink: http://localhost:3000/verify
  passwordResetLink: http://localhost:3000/passwordreset
  emailservice: gmail
  emailadress: houseofmud2022@gmail.com
  emailsecret: ...
  cookiehost: .mud-ga.me

mongodb:
  host: 127.0.0.1
  port: 27017
  user: root
  password: root
