
api:
  port: 43210

hostLink:
  hostAuthKey: SuperSecretKey
  port: 43211

tls:
  use: false
  cert:
    key: /etc/letsencrypt/live/privkey.pem
    cert: /etc/letsencrypt/live/fullchain.pem
    ca: /etc/letsencrypt/live/chain.pem

mongodb:
  url: 127.0.0.1
  port: 27017
  user: root
  password: root
