name: Alpha

supervisorLink:
  url: localhost
  port: 43211
  tls: false
  authKey: SuperSecretKey

amqpAdapter:
  url: mud-ga.me
  port: 5672
  user: guest
  password: guest
  serverExchange: ServerExchange
  clientExchange: ClientExchange

mongodb:
  host: mud-ga.me
  port: 27017
  user: root
  password: OTQzNThne#jM5OHJ2ajcz§OTU3ajQ1O%XQ_1ajc5ajcwOTdo
  database: dev-test